version: '3.8'

services:
  # Defines the mockoon-services container, which hosts mock APIs managed by Mockoon.
  # mockoon-services:
  #   build:
  #     context: ./mockoon-container
  #   networks:
  #     - api_gateway_network
  #   ports:
  #     - "3003:3003" # Exposes port 3003 on the host and forwards it to port 3003 in the container.
  #     - "3004:3004" # Exposes port 3004 on the host and forwards it to port 3004 in the container.
  #     - "3005:3005" # Exposes port 3005 on the host and forwards it to port 3005 in the container.

  # Defines the nginx container, which acts as the API gateway.
  nginx:
    build:
      context: .
    networks:
      - api_gateway_network
    ports:
      - "8080:80" # Exposes port 80 on the host and forwards it to port 80 in the container.

networks:
  # Defines a custom network named api_gateway_network.
  api_gateway_network:
